# Generated by Django 3.2.7 on 2021-09-07 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidopaterno', models.CharField(max_length=255, verbose_name='Apellido Paterno')),
                ('apellidomaterno', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido Materno')),
                ('fechadenacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('especialidad', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellidopaterno', models.CharField(max_length=255, verbose_name='Apellido Paterno')),
                ('apellidomaterno', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido Materno')),
                ('fechadenacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.doctor')),
            ],
        ),
    ]
