# Generated by Django 3.2.7 on 2021-09-07 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['apellidopaterno'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
    ]
