# Generated by Django 3.2.7 on 2021-09-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0004_notas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notas',
            options={'permissions': (('notas', 'Permiso para poder editar/crear/ver/borrar'),)},
        ),
    ]
